export const WORLD_CITIES = [
  "Paris, France",
  "London, United Kingdom",
  "New York City, USA",
  "Tokyo, Japan",
  "Dubai, UAE",
  "Barcelona, Spain",
  "Rome, Italy",
  "Madrid, Spain",
  "Singapore",
  "Amsterdam, Netherlands",
  "Prague, Czech Republic",
  "Seoul, South Korea",
  "Istanbul, Turkey",
  "Bangkok, Thailand",
  "Vienna, Austria",
  "Berlin, Germany",
  "Milan, Italy",
  "Lisbon, Portugal",
  "Los Angeles, USA",
  "Venice, Italy",
  "Florence, Italy",
  "Kyoto, Japan",
  "Athens, Greece",
  "Mumbai, India",
  "Delhi, India",
  "Sydney, Australia",
  "Toronto, Canada",
  "Chicago, USA",
  "San Francisco, USA",
  "Mexico City, Mexico",
  "Rio de Janeiro, Brazil",
  "Buenos Aires, Argentina",
  "Cape Town, South Africa",
  "Cairo, Egypt",
  "Marrakech, Morocco",
  "Bali, Indonesia",
  "Phuket, Thailand",
  "Santorini, Greece",
  "Zurich, Switzerland",
  "Munich, Germany",
  "Stockholm, Sweden",
  "Copenhagen, Denmark",
  "Oslo, Norway",
  "Helsinki, Finland",
  "Reykjavik, Iceland",
  "Dublin, Ireland",
  "Edinburgh, United Kingdom",
  "Vancouver, Canada",
  "Montreal, Canada",
  "Melbourne, Australia",
  "Auckland, New Zealand",
  "Singapore",
  "Hong Kong",
  "Shanghai, China",
  "Beijing, China",
  "Seoul, South Korea",
  "Osaka, Japan",
  "Taipei, Taiwan",
  "Hanoi, Vietnam",
  "Ho Chi Minh City, Vietnam",
  "Kuala Lumpur, Malaysia",
  "Manila, Philippines",
  "Jakarta, Indonesia",
  "Tel Aviv, Israel",
  "Beirut, Lebanon",
  "Amman, Jordan",
  "Abu Dhabi, UAE",
  "Doha, Qatar",
  "Riyadh, Saudi Arabia",
  "Casablanca, Morocco",
  "Nairobi, Kenya",
  "Lagos, Nigeria",
  "Johannesburg, South Africa",
];
